---
- name: User Playbook
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:
  - name: Add user bob
    user:
      name: bob
      comment: "John Smith"
      groups: wheel
      generate_ssh_key: yes
      state: present


    

